Fixes issue #75
pmem/CacheLib pull request #76
Opened 2022-06-07 22:42 UTC by victoria-mcgrath

Use actual tier sizes (rounded down to slab size and decreased by header size) when creating new memory pools

2022-06-08 08:04 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/76#-:-N41KuJe7MYBGWwVCwno:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor and @victoria-mcgrath)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2391 at r1](https://reviewable.io/reviews/pmem/cachelib/76#-N41KlH6855m9h1AxaHK:-N41KlH6855m9h1AxaHL:b-lsnz31) ([raw file](https://github.com/pmem/cachelib/blob/5aa80fd325e64861d819d878c750a10a78ddc062/cachelib/allocator/CacheAllocator-inl.h#L2391)):*
> ```objc
>       for (TierId tid = 0; (tid < numTiers_) && remainingPoolSize;
>            tid++, remainingPoolSize--) {
>         tierPoolSizes[tid]++;
> ```

Can this be off only be one?


<!-- Sent from Reviewable.io -->

2022-06-09 15:38 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/76#-:-N486NEPCHhQOWaXt_g6:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-06-10 08:31 UTC, igchor requested changes
In such case, I think it would be good to add some more tests with different ratios. For example X:Y where X and Y are in range from 1 to 1000.

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/76#-:-N4Bj3kAEXZvRzejVAAl:bkcslzr)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2022-06-13 12:00 UTC, igchor commented
@victoria-mcgrath would you be able to add a few more tests with different ratios (e.g. all combinations from 1 to 100)?

2022-06-13 16:29 UTC, victoria-mcgrath commented
yes, I'll work on test coverage before merging.





<!-- Sent from Reviewable.io -->

2022-06-17 13:12 UTC, victoria-mcgrath commented
I reworked tests to make them go over a few more combinations of sizes and ratios.





<!-- Sent from Reviewable.io -->

2022-06-29 11:44 UTC, igchor commented
rebased version on: https://github.com/pmem/CacheLib/pull/88

2022-06-29 11:44 UTC, closed without merging