Add memory usage statistics for slabs and allocation classes
pmem/CacheLib pull request #91
Opened 2022-07-06 11:47 UTC by igchor

Printing those stats can be enabled by passing `-report_memory_usage_stats` to cachebench

Sample output:
```
tid 0 free slabs : 0.00%
tid 1 free slabs : 0.00%
tid 0 pid 0 cid   0    64.00B memorySize:     0.00B
tid 0 pid 0 cid   1    96.00B memorySize:    36.00MB
tid 0 pid 0 cid   2   144.00B memorySize:   124.00MB
tid 0 pid 0 cid   3   216.00B memorySize:   276.00MB
tid 0 pid 0 cid   4   328.00B memorySize:   744.00MB
tid 0 pid 0 cid   5   496.00B memorySize:   992.00MB
tid 0 pid 0 cid   6   744.00B memorySize:   508.00MB
tid 0 pid 0 cid   7     1.09KB memorySize:   416.00MB
tid 0 pid 0 cid   8     1.64KB memorySize:   212.00MB
tid 0 pid 0 cid   9     2.46KB memorySize:   132.00MB
tid 0 pid 0 cid  10     3.70KB memorySize:   152.00MB
tid 0 pid 0 cid  11     5.55KB memorySize:   136.00MB
tid 0 pid 0 cid  12     8.32KB memorySize:    36.00MB
tid 0 pid 0 cid  13    12.48KB memorySize:    20.00MB
tid 0 pid 0 cid  14    18.78KB memorySize:    20.00MB
tid 0 pid 0 cid  15    28.24KB memorySize:    32.00MB
tid 0 pid 0 cid  16    42.66KB memorySize:   200.00MB
tid 0 pid 0 cid  17    64.00KB memorySize:    36.00MB
tid 0 pid 0 cid  18    97.52KB memorySize:    12.00MB
tid 0 pid 0 cid  19   151.70KB memorySize:     4.00MB
tid 0 pid 0 cid  20   227.55KB memorySize:     4.00MB
tid 0 pid 0 cid  21   372.36KB memorySize:     0.00B
tid 0 pid 0 cid  22   585.14KB memorySize:     0.00B
tid 0 pid 0 cid  23     1.00MB memorySize:     0.00B
tid 1 pid 0 cid   0    64.00B memorySize:     0.00B
tid 1 pid 0 cid   1    96.00B memorySize:    40.00MB
tid 1 pid 0 cid   2   144.00B memorySize:   124.00MB
tid 1 pid 0 cid   3   216.00B memorySize:   272.00MB
tid 1 pid 0 cid   4   328.00B memorySize:   760.00MB
tid 1 pid 0 cid   5   496.00B memorySize:   984.00MB
tid 1 pid 0 cid   6   744.00B memorySize:   508.00MB
tid 1 pid 0 cid   7     1.09KB memorySize:   424.00MB
tid 1 pid 0 cid   8     1.64KB memorySize:   208.00MB
tid 1 pid 0 cid   9     2.46KB memorySize:   136.00MB
tid 1 pid 0 cid  10     3.70KB memorySize:   148.00MB
tid 1 pid 0 cid  11     5.55KB memorySize:   132.00MB
tid 1 pid 0 cid  12     8.32KB memorySize:    32.00MB
tid 1 pid 0 cid  13    12.48KB memorySize:    16.00MB
tid 1 pid 0 cid  14    18.78KB memorySize:    20.00MB
tid 1 pid 0 cid  15    28.24KB memorySize:    32.00MB
tid 1 pid 0 cid  16    42.66KB memorySize:   208.00MB
tid 1 pid 0 cid  17    64.00KB memorySize:    32.00MB
tid 1 pid 0 cid  18    97.52KB memorySize:    12.00MB
tid 1 pid 0 cid  19   151.70KB memorySize:     4.00MB
tid 1 pid 0 cid  20   227.55KB memorySize:     0.00B
tid 1 pid 0 cid  21   372.36KB memorySize:     0.00B
tid 1 pid 0 cid  22   585.14KB memorySize:     0.00B
tid 1 pid 0 cid  23     1.00MB memorySize:     0.00B
tid 0 pid 0 cid   0    64.00B free: 100.00%
tid 0 pid 0 cid   1    96.00B free: 0.00%
tid 0 pid 0 cid   2   144.00B free: 0.00%
tid 0 pid 0 cid   3   216.00B free: 0.00%
tid 0 pid 0 cid   4   328.00B free: 0.00%
tid 0 pid 0 cid   5   496.00B free: 0.00%
tid 0 pid 0 cid   6   744.00B free: 0.01%
tid 0 pid 0 cid   7     1.09KB free: 0.02%
tid 0 pid 0 cid   8     1.64KB free: 0.02%
tid 0 pid 0 cid   9     2.46KB free: 0.02%
tid 0 pid 0 cid  10     3.70KB free: 0.04%
tid 0 pid 0 cid  11     5.55KB free: 0.06%
tid 0 pid 0 cid  12     8.32KB free: 0.06%
tid 0 pid 0 cid  13    12.48KB free: 0.03%
tid 0 pid 0 cid  14    18.78KB free: 0.04%
tid 0 pid 0 cid  15    28.24KB free: 0.02%
tid 0 pid 0 cid  16    42.66KB free: 0.01%
tid 0 pid 0 cid  17    64.00KB free: 0.00%
tid 0 pid 0 cid  18    97.52KB free: 0.00%
tid 0 pid 0 cid  19   151.70KB free: 0.00%
tid 0 pid 0 cid  20   227.55KB free: 61.11%
tid 0 pid 0 cid  21   372.36KB free: 100.00%
tid 0 pid 0 cid  22   585.14KB free: 100.00%
tid 0 pid 0 cid  23     1.00MB free: 100.00%
tid 1 pid 0 cid   0    64.00B free: 100.00%
tid 1 pid 0 cid   1    96.00B free: 0.00%
tid 1 pid 0 cid   2   144.00B free: 0.00%
tid 1 pid 0 cid   3   216.00B free: 0.00%
tid 1 pid 0 cid   4   328.00B free: 0.00%
tid 1 pid 0 cid   5   496.00B free: 0.00%
tid 1 pid 0 cid   6   744.00B free: 0.01%
tid 1 pid 0 cid   7     1.09KB free: 0.02%
tid 1 pid 0 cid   8     1.64KB free: 0.02%
tid 1 pid 0 cid   9     2.46KB free: 0.02%
tid 1 pid 0 cid  10     3.70KB free: 0.04%
tid 1 pid 0 cid  11     5.55KB free: 0.06%
tid 1 pid 0 cid  12     8.32KB free: 0.06%
tid 1 pid 0 cid  13    12.48KB free: 0.03%
tid 1 pid 0 cid  14    18.78KB free: 0.04%
tid 1 pid 0 cid  15    28.24KB free: 0.02%
tid 1 pid 0 cid  16    42.66KB free: 0.01%
tid 1 pid 0 cid  17    64.00KB free: 0.00%
tid 1 pid 0 cid  18    97.52KB free: 0.00%
tid 1 pid 0 cid  19   151.70KB free: 0.00%
tid 1 pid 0 cid  20   227.55KB free: 100.00%
tid 1 pid 0 cid  21   372.36KB free: 100.00%
tid 1 pid 0 cid  22   585.14KB free: 100.00%
tid 1 pid 0 cid  23     1.00MB free: 100.00%
```

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/cachelib/91)

2022-07-06 19:53 UTC, raema commented
Hi @igchor, most of the metrics have the name and value separated by a single colon like:
'Hit Ratio     :  92.07%'
That metric appears in prometheus named 'hit_ratio'

For the line below, I'm thinking how we would parse this output into 'name, value' for prometheus
tid :  0, pid :  0, cid :    0, alloc size :    64.00B, memory size :     0.00B, free : 100.00%

If we want to follow the same format as other metrics maybe we could use this format:
tid0 pid0 cid0 64.00KB size    :     0.00B
tid0 pid0 cid0 64.00KB free  :     100.00%

Does it make sense to change the stats output to use this format or something like this?  Our existing scripts will automatically collect new metrics output in this format.

2022-07-06 23:01 UTC, guptask commented
*[`cachelib/allocator/CacheAllocator-inl.h` line 2510 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KjixF05I_atkXpdiL:-N6KjixF05I_atkXpdiM:b80y54m) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/CacheAllocator-inl.h#L2510)):*
> ```objc
> 
> template <typename CacheTrait>
> double CacheAllocator<CacheTrait>::slabsFreePercentage(TierId tid) const
> ```

should this name have approx term in it as well ?


<!-- Sent from Reviewable.io -->

2022-07-06 23:30 UTC, guptask commented
*[`cachelib/allocator/memory/AllocationClass.cpp` line 54 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6Kpdud43xYxjc-IQhg:-N6Kpdud43xYxjc-IQhh:b2dijzy) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/memory/AllocationClass.cpp#L54)):*
> ```cpp
>       slabAlloc_(s),
>       freedAllocations_{slabAlloc_.createSingleTierPtrCompressor<FreeAlloc>()} {
>   curAllocatedSlabs_ = allocatedSlabs_.size();
> ```

Do you want to use memory_order_seq_cst order here for atomic store ? Otherwise store() is needed if you want to use something like memory_order_release order.


<!-- Sent from Reviewable.io -->

2022-07-06 23:31 UTC, guptask commented
*[`cachelib/allocator/memory/AllocationClass.cpp` line 126 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KqZFd-_tjzhWfAvL-:-N6KqZFd-_tjzhWfAvL0:bi3prml) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/memory/AllocationClass.cpp#L126)):*
> ```cpp
>   }
> 
>   curAllocatedSlabs_ = allocatedSlabs_.size();
> ```

same as above comment about memory order if using assignment operator instead of atomic store().


<!-- Sent from Reviewable.io -->

2022-07-06 23:37 UTC, guptask commented
*[`cachelib/allocator/memory/AllocationClass.cpp` line 741 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KrqEf-dIm6WTph5vp:-N6KrqEf-dIm6WTph5vq:b-p4b9jn) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/memory/AllocationClass.cpp#L741)):*
> ```cpp
> 
> double AllocationClass::approxFreePercentage() const {
>   if (getNumSlabs() == 0)
> ```

Cosmetic review : I suggest using curly braces even if there is one line after if statement.


<!-- Sent from Reviewable.io -->

2022-07-06 23:53 UTC, guptask commented
*[`cachelib/allocator/tests/CacheBaseTest.cpp` line 36 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KvVHwEQjVelXpvn7r:-N6KvVHwEQjVelXpvn7s:b-80ncgr) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/tests/CacheBaseTest.cpp#L36)):*
> ```cpp
>   const MemoryPool& getPool(PoolId) const override { return memoryPool_; }
>   PoolStats getPoolStats(PoolId) const override { return PoolStats(); }
>   AllocationClassBaseStat getAllocationClassStats(TierId tid, PoolId, ClassId) const {return AllocationClassBaseStat();};
> ```

am not sure why this line passed the clang-format check ? the character count is high.


<!-- Sent from Reviewable.io -->

2022-07-07 00:02 UTC, guptask reviewed
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/91)* status: all files reviewed, 5 unresolved discussions (waiting on @byrnedj and @igchor)



<!-- Sent from Reviewable.io -->

2022-07-07 15:57 UTC, igchor reviewed
@raema Ok, I changed it to how you suggested. Please let me now if this is OK.

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/91#-:-N6OEAQh3y31q6Xui7wq:bckprc2)* status: 7 of 15 files reviewed, 5 unresolved discussions (waiting on @byrnedj and @guptask)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2510 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KjixF05I_atkXpdiL:-N6OGH8P5zc_-jIZA6BS:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/CacheAllocator-inl.h#L2510)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

should this name have approx term in it as well ?
</blockquote></details>

Done.
___
*[`cachelib/allocator/memory/AllocationClass.cpp` line 54 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6Kpdud43xYxjc-IQhg:-N6OEKJH5DVZWRItOE_K:b-if01y0) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/memory/AllocationClass.cpp#L54)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

Do you want to use memory_order_seq_cst order here for atomic store ? Otherwise store() is needed if you want to use something like memory_order_release order.
</blockquote></details>

It's just for readability, the order doesn't matter here since it's ctor.
___
*[`cachelib/allocator/memory/AllocationClass.cpp` line 126 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KqZFd-_tjzhWfAvL-:-N6OEQ1n1o43bPoJ7dVJ:b2nreh6) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/memory/AllocationClass.cpp#L126)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

same as above comment about memory order if using assignment operator instead of atomic store().
</blockquote></details>

Same as above.
___
*[`cachelib/allocator/memory/AllocationClass.cpp` line 741 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KrqEf-dIm6WTph5vp:-N6OFUAw-X7D8tH-unj9:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/memory/AllocationClass.cpp#L741)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

Cosmetic review : I suggest using curly braces even if there is one line after if statement.
</blockquote></details>

Done.
___
*[`cachelib/allocator/tests/CacheBaseTest.cpp` line 36 at r1](https://reviewable.io/reviews/pmem/cachelib/91#-N6KvVHwEQjVelXpvn7r:-N6OFQ6s8nIcONLcZf_1:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/891ad6bb7d096d6a046bcc5a7dfe0231ccc66284/cachelib/allocator/tests/CacheBaseTest.cpp#L36)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

am not sure why this line passed the clang-format check ? the character count is high.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 20:16 UTC, raema commented
> @raema Ok, I changed it to how you suggested. Please let me now if this is OK.
> 
This output looks good. Thanks!

2022-07-08 12:22 UTC, byrnedj commented on cachelib/allocator/PromotionStrategy.h
> +    auto maxBatch = *std::max_element(batches.begin(), batches.end());
will segfault if batches.size() == 0

2022-07-08 12:24 UTC, byrnedj requested changes
line 52 of PromotionStrategey.h will segfault if vector is empty. did you mean to include PromotionStrategy.h on this PR?

2022-07-08 16:20 UTC, igchor reviewed
Good catch, I commited this file by mistake.

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/91#-:-N6TanTdAGyFLYYVjCta:b-21vhor)* status: 7 of 15 files reviewed, 6 unresolved discussions (waiting on @byrnedj and @guptask)

___
*[`cachelib/allocator/PromotionStrategy.h` line 52 at r2](https://reviewable.io/reviews/pmem/cachelib/91#-N6ONJjbmYez-0fnRwlt-r2-52:-N6TaqZT56mTgkwJKR7J:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/9215ab0a6c746cb60593abb62f7f17223813f1be/cachelib/allocator/PromotionStrategy.h#L52)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

will segfault if batches.size() == 0
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-08 16:32 UTC, byrnedj approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/91#-:-N6TdRa-14CrNt30oQLw:bnfp4nl)* status: 7 of 15 files reviewed, 5 unresolved discussions (waiting on @byrnedj and @guptask)



<!-- Sent from Reviewable.io -->

2022-07-11 14:55 UTC, merged